---
- name: Create configuration directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ pihole_host_pihole_dir }}"
    - "{{ pihole_host_dnsmasq_dir }}"

- name: Get pihole password from password store
  set_fact:
    pihole_webpassword: "{{ lookup('community.general.passwordstore', pihole_passwordstore_prefix + ansible_default_ipv4.address, missing='warn') }}"
  when: pihole_passwordstore_enabled is defined and pihole_passwordstore_enabled

- name: Copy pihole systemd service
  template:
    src: pihole.service.j2
    dest: "/etc/systemd/system/{{ pihole_service_name }}.service"
    backup: True
  notify: pihole restart
