---

- name: Create configuration directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ pihole_host_pihole_dir }}"
    - "{{ pihole_host_dnsmasq_dir }}"

- name: Copy pihole systemd service
  template:
    src: pihole.service.j2
    dest: "/etc/systemd/system/{{ pihole_service_name }}.service"
    backup: True
  notify: pihole restart
