- name: Install pihole service
  become: true
  become_user: root
  include: install.yml
  when: not flush_all

- name: Remove pihole service
  become: true
  become_user: root
  include: uninstall.yml
  when: flush_all
